# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Videos: cache + seeking
[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Accept-Ranges = "bytes"

# Images: long cache
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Keep HTML fresh
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
